---

name: Cowsay Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cowsay

    - name: Create Cowsay file
      run: |
        echo ${{ secrets.COWSAY_MESSAGE }} | cowsay > /var/www/html/cowsay.txt


    
    - name: test output
      run: |
        grep "_,,_" cowsay.txt
    
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
      with:
        path: cowsay.txt
        name: notrevache

  deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: /var/www/html/
          name: notrevache




