name: Cowsay Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cowsay 
      run: sudo apt-get update && sudo apt-get install -y cowsay

    - name: Create Cowsay variable
      run: |
        echo "${{ vars.COWSAY_MESSAGE }}" | cowsay > cowsay.txt

    - name: Print Cowsay output 
      run: cat cowsay.txt

    - name: Test output
      run: |
        grep "(oo)" cowsay.txt

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-artifact@v4
      with:
        path: cowsay.txt
        name: notrevache

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Ensure artifact directory exists
        run: mkdir -p /var/www/html/

      - name: Check directory permissions
        run: ls -ld /var/www/html

      - name: Check network connectivity
        run: ping -c 4 github.com

      - name: Download artifact with retries
        run: |
          for i in {1..5}; do
            actions/download-artifact@v4 --path /var/www/html/ --name notrevache && break
            echo "Retry $i/5 failed. Retrying in 10 seconds..."
            sleep 10
          done
        shell: bash

      - name: Print downloaded files
        run: ls -la /var/www/html/

      - name: Write Cowsay file
        run: echo ${{ secrets.COWSAY_MESSAGE }} | cowsay > /var/www/html/cowsay.txt
