---

name: Cowsay Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cowsay 
      run: sudo apt-get update && sudo apt-get install -y cowsay

    - name: Create Cowsay file
      run: |
        echo "${{ vars.COWSAY_MESSAGE }}" | cowsay > cowsay.txt

    - name: Print Cowsay output 
      run: cat cowsay.txt

    - name: Test output
      run: |
        grep "_,,_" cowsay.txt

    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-artifact@v4
      with:
        path: cowsay.txt
        name: notrevache

  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: /var/www/html/
          name: notrevache

      - name: Grant write permissions
        run: sudo chmod 777 /var/www/html/cowsay.txt
      
      - name: Write Cowsay file
        run: echo ${{ secrets.COWSAY_MESSAGE }} | cowsay > /var/www/html/cowsay.txt
