name: ci

on:
  push:
    

jobs:
  login:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout-file
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CHRIST_TOKEN_MD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/notreache:latest